# -----------------------------------------------------------------------------
# Pi Hole Server Variables
#
# Pi Hole is served by an Ubuntu LXC container.
# -----------------------------------------------------------------------------
---

resolv_nameservers:
  - "208.67.222.222"
  - "208.67.220.220"
